### ISSUE TITLE
MVP todo list

### ISSUE THREAD

**Issue by JustinByrne** [JustinByrne/my-blog#1]
The following need to be done to make the MVP.

- [ ] Add an Admin page
- [ ] Add a Settings page to the admin section
- [ ] Add a way to change the social media links
